name: Close Issue on Completed PR

on: 
  pull_request:
    types: closed
    branches: 
      - main

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      
      - name: close issue
        run: |
          gh issue close 1 --comment "Auto-closing issue" 
        env:
          GH_TOKEN: ${{ github.token }}


          
