name: Close Issue on Completed PR

on: 
  pull_request:
    types: closed
    branches: 
      - main

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: close issue
        run: |
          gh issue close --comment "Auto-closing issue" "1"
        env:
          GH_TOKEN: ${{ github.token }}


          
