name: Move Issue

on:
  issues: 
    types:
      - assigned

jobs:
  move-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Actions-Issues_Automation
          column: In Progress
          repo-token: ${{ secrets.GITHUBTOKEN }}
        
  
